Bug Fix V1
React useEffect causing: Can't perform a React state
update on an unmounted component

TypeError: Cannot read properties of null (reading 'style')